name: continuous integration

on:
  workflow_call:
    inputs:
      slack-channel:
        description: slack channel for send message
        required: true
        type: string
      
      use-gpu:
        description: run test on gpu
        type: boolean
        required: false
        default: false

    secrets:
      extra-index-url:
        description: pipy extra index url
        required: true

      trusted-host:
        description: pipy trusted host
        required: true

      slack-token:
        description: slack token for send message
        required: true


jobs:
  check-version-and-linter:
    runs-on: ubuntu-20.04
    name: version check and linter

    steps:
      - name: Checkout the CI-target repository
        uses: actions/checkout@v3

      - name: Checkout the action repository
        uses: actions/checkout@v3
        with:
          repository: teamdable/vv-continuous-integration
          path: action/
      
      - name: 변경된 파일 체크
        id: changed-files
        uses: tj-actions/changed-files@v18.7
      
      - name: Install packages for report
        if: steps.changed-files.outputs.all_changed_files
        run: |
          python -m pip install --upgrade pip
          pip install -r action/requirements.txt --trusted-host ${{ secrets.trusted-host }} --extra-index-url ${{ secrets.extra-index-url }}

      - name: Version 파일이 변경되었는 지 체크
        if: steps.changed-files.outputs.all_changed_files
        run: |
          ./action/version-check \
            --modified-files ${{ steps.changed-files.outputs.all_changed_files }} \
            --token ${{ secrets.slack-token }} \
            --channel ${{ inputs.slack-channel }} \
            --repo-name ${{ github.event.repository.name }} \
            --branch-name ${{ github.event.pull_request.head.ref }} \
            --base-name ${{ github.event.pull_request.base.ref }} \
            --base-sha ${{ github.event.pull_request.base.sha }} \
            --pull-request-number ${{ github.event.number }}
      
      - name: Pylint Test
        if: steps.changed-files.outputs.all_changed_files
        run: |
          ./action/pylint-test \
            --modified-files ${{ steps.changed-files.outputs.all_changed_files }} \
            --min-score 8.0 \
            --token ${{ secrets.slack-token }} \
            --channel ${{ inputs.slack-channel }} \
            --repo-name ${{ github.event.repository.name }} \
            --branch-name ${{ github.event.pull_request.head.ref }} \
            --base-name ${{ github.event.pull_request.base.ref }} \
            --base-sha ${{ github.event.pull_request.base.sha }} \
            --pull-request-number ${{ github.event.number }}
      
      - name: Eslint test
        if: steps.changed-files.outputs.all_changed_files
        run: |
          ./action/eslint-test \
            --modified-files ${{ steps.changed-files.outputs.all_changed_files }} \
            --min-score 8.0 \
            --token ${{ secrets.slack-token }} \
            --channel ${{ inputs.slack-channel }} \
            --repo-name ${{ github.event.repository.name }} \
            --branch-name ${{ github.event.pull_request.head.ref }} \
            --base-name ${{ github.event.pull_request.base.ref }} \
            --base-sha ${{ github.event.pull_request.base.sha }} \
            --pull-request-number ${{ github.event.number }}

    
  on-self-hosted-runner:
    if: ${{ inputs.use-gpu }}
    needs: check-version-and-linter
    runs-on: self-hosted
    name: run test code on self hosted runner

    steps:
      - name: Checkout the CI-target repository
        uses: actions/checkout@v3

      - name: Checkout the action repository
        uses: actions/checkout@v3
        with:
          repository: teamdable/vv-continuous-integration
          path: action/

      - name: Install packages for report
        run: |
          python -m pip install --upgrade pip
          pip install -r action/requirements.txt

      - name: Build Test Environment
        run: |
          ./action/builder \
            --trusted-host ${{ secrets.trusted-host }} \
            --extra-index-url ${{ secrets.extra-index-url }}
      
      - name: Run Test Codes
        run: |
          ./action/run-test \
            --token ${{ secrets.slack-token }} \
            --channel ${{ inputs.slack-channel }} \
            --repo-name ${{ github.event.repository.name }} \
            --branch-name ${{ github.event.pull_request.head.ref }} \
            --base-name ${{ github.event.pull_request.base.ref }} \
            --base-sha ${{ github.event.pull_request.base.sha }} \
            --pull-request-number ${{ github.event.number }}
  
  on-github-actions-runner:
    if: ${{ ! inputs.use-gpu }}
    needs: check-version-and-linter
    runs-on: ubuntu-20.04
    name: run test code on github actions runner

    steps:
      - name: Checkout the CI-target repository
        uses: actions/checkout@v3

      - name: Checkout the action repository
        uses: actions/checkout@v3
        with:
          repository: teamdable/vv-continuous-integration
          path: action/
      
      - name: Install packages for report
        run: |
          python -m pip install --upgrade pip
          pip install -r action/requirements.txt --trusted-host ${{ secrets.trusted-host }} --extra-index-url ${{ secrets.extra-index-url }}
      
      - name: Build Test Environment
        run: |
          ./action/builder \
            --trusted-host ${{ secrets.trusted-host }} \
            --extra-index-url ${{ secrets.extra-index-url }}

      - name: Run Test Codes
        run: |
          ./action/run-test \
            --token ${{ secrets.slack-token }} \
            --channel ${{ inputs.slack-channel }} \
            --repo-name ${{ github.event.repository.name }} \
            --branch-name ${{ github.event.pull_request.head.ref }} \
            --base-name ${{ github.event.pull_request.base.ref }} \
            --base-sha ${{ github.event.pull_request.base.sha }} \
            --pull-request-number ${{ github.event.number }}