name: continuous integration

on:
  workflow_call:
    inputs:
      slack-channel:
        description: slack channel for send message
        required: true
        type: string

      version-file:
        description: version file name
        required: true
        type: string


    secrets:
      extra-index-url:
        description: pipy extra index url
        required: true

      trusted-host:
        description: pipy trusted host
        required: true

      slack-token:
        description: slack token for send message
        required: true


jobs:
  version-check:
    runs-on: ubuntu-20.04
    name: version check and linter

    steps:
      - name: Checkout the deploy-target repository
        uses: actions/checkout@v3

      - name: Checkout the action repository
        uses: actions/checkout@v3
        with:
          repository: teamdable/vv-continuous-integration
          path: action/
      
      - name: Setup Python Environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      
      - name: Install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r action/requirements.txt --trusted-host ${{ secrets.trusted-host }} --extra-index-url ${{ secrets.extra-index-url }}
      
      - name: 변경된 파일 체크
        id: changed-files
        uses: tj-actions/changed-files@v18.7
        with:
          files_ignore: |
            *.github/*
        
      - name: Check .version 변경된 라인 체크
        if: contains(steps.changed-files.outputs.all_changed_files, ${{ inputs.version-file }} )
        run: |
          save_path="$(basename -a ${{ inputs.version-file }} ).diff"
          git diff ${{ github.event.pull_request.base.sha }} ${{ inputs.version-file }} > $save_path

      - name: Version 파일이 변경되었는 지 체크
        if: steps.changed-files.outputs.all_changed_files
        run: |
          ./action/version-check \
            --version-file ${{ inputs.version-file }} \
            --token ${{ secrets.slack-token }} \
            --channel ${{ inputs.slack-channel }} \
            --repo-name ${{ github.event.repository.name }} \
            --branch-name ${{ github.event.pull_request.head.ref }} \
            --target-name ${{ github.event.pull_request.base.ref }} \
            --pull-request-number ${{ github.event.number }}
